### ISSUE TITLE
TypeError: object of type 'float' has no len()

### ISSUE THREAD

**Issue by WouterKr** [FlyingDiver/Indigo-Shims#5]
Trying to get the sensor values of a Mi Flora in Indigo. Values are pasted from the broker -> trigger -> device. When there is a match 

```
>  MQTT Shims Debug                received notification of MQTT message type ##MiFlora## from 
>    MQTT Shims Debug                MiFlora Moisture: processMessages: '##MiFlora##' beacons/BTMQTT_Woonkamer/BTtoMQTT/C47C8D6B27F6 -> {"tem":23.1}
>    MQTT Shims Debug                MiFlora Moisture: shimValueSensor, key = moi, data = {u'tem': 23.1}, value = None
>    MQTT Shims Debug                MiFlora Moisture: state_key moi not found in payload
>    MQTT Shims Debug                MiFlora Lux: processMessages: '##MiFlora##' beacons/BTMQTT_Woonkamer/BTtoMQTT/C47C8D6B27F6 -> {"tem":23.1}
>    MQTT Shims Debug                MiFlora Lux: shimValueSensor, key = lux, data = {u'tem': 23.1}, value = None
>    MQTT Shims Debug                MiFlora Lux: state_key lux not found in payload
>    MQTT Shims Debug                MiFlora Temp: processMessages: '##MiFlora##' beacons/BTMQTT_Woonkamer/BTtoMQTT/C47C8D6B27F6 -> {"tem":23.1}
>    MQTT Shims Debug                MiFlora Temp: shimValueSensor, key = tem, data = {u'tem': 23.1}, value = 23.1
>    MQTT Shims Debug                MiFlora Temp: Updating state to 23.1
>    MQTT Shims Error                Error in plugin execution runConcurrentThread:
> 
> Traceback (most recent call last):
>   File "plugin.py", line 87, in runConcurrentThread
>   File "plugin.py", line 112, in processMessages
>   File "plugin.py", line 342, in update
> TypeError: object of type 'float' has no len()
> 
>    MQTT Shims Error                plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
> 
```

**Comment by FlyingDiver** [comment]
Can you post a screenshot of the config dialog for those devices?

**Comment by FlyingDiver** [comment]
Do you have something in the multi-states key field?  You should not for that payload.

**Comment by WouterKr** [comment]
I did not have something in that field but then I got this error:

```
   MQTT Shims Debug                MiFlora Moisture: processMessages: '##MiFlora##' beacons/BTMQTT_Woonkamer/BTtoMQTT/C47C8D6B27F6 -> {"moi":0}
   MQTT Shims Debug                MiFlora Moisture: shimValueSensor, key = moi, data = {u'moi': 0}, value = 0
   MQTT Shims Debug                MiFlora Moisture: Updating state to 0.0
   Error                           device "MiFlora Moisture" state key sensorValue not defined (ignoring update request)
   Error                           device "MiFlora Moisture" state key sensorValue not defined (ignoring update request)
```
I put a key in that field and then the value was processed. But then I got this one.

Changed it back again and all is working. 
Oh, wait, I recreated these devices because I thought it could be related to the fact I copied them from other Shims devices

I am sorry! I did not think of not entering a key in that field.

**Comment by FlyingDiver** [comment]
So it works fine with no entry in field?

**Comment by WouterKr** [comment]
Yes it does. No more errors. Do not know why I got the first error; must have been a configuration error on my side also.

Thanks

**Comment by FlyingDiver** [comment]
I’m going to leave this open to improve the error checking.

**Comment by FlyingDiver** [comment]
Added better error checking for the Multi-States Key.  Will be in next release.
